dependencies:
  - Openzeppelin/openzeppelin-contracts@4.3.0
compiler:
  solc:
    remappings:
      '@openzeppelin=Openzeppelin/openzeppelin-contracts@4.3.0'
network:
  default: development
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
  from_key2: ${PRIVATE_KEY_2}
  mnemonic: ${MNEMONIC}